# Generated by Django 4.2.7 on 2023-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email',
            field=models.EmailField(max_length=254),
        ),
    ]
